name: Deploy Site

on:
  push:
    branches: [master]

jobs:
  deploy-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: make
      - uses: actions/setup-node@v3
        with:
          node-version: 24.2.0
      - name: Install puppeteer
        run: npx puppeteer browsers install chrome
      - name: Build site
        run: make build-docs

      - name: Deploy site
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          branch: gh-page
          folder: display
          single-commit: true
          clean: true
